name: forte

dependencies:
    - pip>=19.0
    - pybind11
    - gcc
    - libgcc
    - cmake
    - numpy
    - scipy
    - eigen
    - boost
    - pydantic
    - pyyaml
    - py-cpuinfo
    - hdf5
    - yaml
    - pytest
    - conda-forge::lcov
    - conda-forge/label/libint_dev::libint
    #-psi4::libint2  # high AM
