name: forte

dependencies:
    - python=3.10
    - pip>=19.0
    - pybind11
    - cmake
    - numpy
    - scipy
    - eigen
    - boost
    - pydantic
    - pyyaml
    - py-cpuinfo
    - hdf5
    - yaml
    - pytest
    - conda-forge::lcov
