#!/bin/bash

# hook to run clang-format
CLANG_FORMAT_BIN=$(which clang-format)
if [ -n "$CLANG_FORMAT_BIN" ]; then
    CXX_CHANGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -Ee "\.((cc|h))$")
    echo "Formatting" $CXX_CHANGED_FILES
    $CLANG_FORMAT_BIN -i -style=file ${CXX_CHANGED_FILES}
else
    echo "clang-format not found in your path. Skipping formatting."
fi
