#! usr/bin/env bash


ls
status=$?
ls -a
statu=$?
echo $status
echo $statu
if [ $status -eq 0 ] && [ $statu -eq 0 ];
then
  echo "Successfully created file"
else
  echo "Could not create file" >&2
  exit 1
fi
